[package]
name = "quail"
version = "0.0.1"
edition = "2018"

[dependencies]
#ark-groth16 = {version="0.2.0", default-features = false }
ark-groth16 = {path="./lib/groth16",version="0.2.0"}
ark-ff = { version = "^0.2.0", default-features = false }
ark-std = { version = "^0.2.0", default-features = false }
ark-ec = { version = "^0.2.0", default-features = false }
ark-bls12-381 = { version = "^0.2.0", default-features = false, features = ["curve"] }
ark-relations = { version = "^0.2.0", default-features = false }
ark-serialize= { version = "^0.2.0", default-features = false }

log = "0.4"

merkle_light = "^0.3.1"
rust-crypto = "^0.2"
rsa = "0.5.0"
rand = "0.8.0"

[[bin]]
name = "proof"
path = "src/proof_generation/proof.rs"

[[bin]]
name = "server"
path = "src/server.rs"
[[bin]]
name = "serverpit"
path = "src/server_pit.rs"
